// Auto-generated by scripts/generate_challenge.py
#include <iostream>
#include <string>
#include <vector>
#include "picosha2.h"

// Expected rolling SHA-256 hashes for each step
const std::string EXPECTED_HASH_0 = "ecebe9dfe1aa99e55029c50d8d8c8038530f157dbbf2c0cd42f9a2969ec6732b";
const std::string EXPECTED_HASH_1 = "c23808cb02b93de5a8befe1678937e30d4633bec2fd076f7667cb5c47ae063bb";
const std::string EXPECTED_HASH_2 = "0ac0bd52c1dc5c1275adbf75b58d74d36170e208d80fbe257172a75d5bd57c51";
const std::string EXPECTED_HASH_3 = "21cc6294913987c2a9c7648257142abcc3e00443344c1c2d3732ab0c46ec9d29";
const std::string EXPECTED_HASH_4 = "6c9193f62c19d6d248a0c8550e74f287ed2092364959377a9e513451c18959b4";
const std::string EXPECTED_HASH_5 = "1d81b8dacbe1a7e56705effaa8c2ce5f42bc88de26cfed4540618709358872fe";

// Global cumulative state and history stack
std::string cumulative_state = "";
std::vector<std::string> jump_history;

// Step match flags
bool step_0_matched = false;
bool step_1_matched = false;
bool step_2_matched = false;
bool step_3_matched = false;
bool step_4_matched = false;
bool step_5_matched = false;

void update_state_matching() {
    step_0_matched = false;
    step_1_matched = false;
    step_2_matched = false;
    step_3_matched = false;
    step_4_matched = false;
    step_5_matched = false;
    std::string hash_out;
    if (cumulative_state.length() >= 6) {
        picosha2::hash256_hex_string(cumulative_state.substr(0, 6), hash_out);
        if (hash_out == EXPECTED_HASH_0) step_0_matched = true;
    }
    if (cumulative_state.length() >= 12 && step_0_matched) {
        picosha2::hash256_hex_string(cumulative_state.substr(0, 12), hash_out);
        if (hash_out == EXPECTED_HASH_1) step_1_matched = true;
    }
    if (cumulative_state.length() >= 18 && step_1_matched) {
        picosha2::hash256_hex_string(cumulative_state.substr(0, 18), hash_out);
        if (hash_out == EXPECTED_HASH_2) step_2_matched = true;
    }
    if (cumulative_state.length() >= 24 && step_2_matched) {
        picosha2::hash256_hex_string(cumulative_state.substr(0, 24), hash_out);
        if (hash_out == EXPECTED_HASH_3) step_3_matched = true;
    }
    if (cumulative_state.length() >= 30 && step_3_matched) {
        picosha2::hash256_hex_string(cumulative_state.substr(0, 30), hash_out);
        if (hash_out == EXPECTED_HASH_4) step_4_matched = true;
    }
    if (cumulative_state.length() >= 36 && step_4_matched) {
        picosha2::hash256_hex_string(cumulative_state.substr(0, 36), hash_out);
        if (hash_out == EXPECTED_HASH_5) step_5_matched = true;
    }
}

// Jump function for Chunk 0: "Saltar"
void jump_to_venice() {
    // Mangled storage with fixed PRNG seed (1337)
    char scrambled[6] = { 0x61, 0x53, 0x74, 0x6c, 0x72, 0x61 };
    char restored[6];
    restored[0] = scrambled[1];
    restored[1] = scrambled[0];
    restored[2] = scrambled[3];
    restored[3] = scrambled[2];
    restored[4] = scrambled[5];
    restored[5] = scrambled[4];
    std::string chunk = std::string(restored, 6);
    cumulative_state += chunk;
    jump_history.push_back(chunk);
    update_state_matching();
}

// Jump function for Chunk 1: "e_e_di"
void jump_to_florence() {
    // Mangled storage with fixed PRNG seed (1338)
    char scrambled[6] = { 0x65, 0x5f, 0x64, 0x65, 0x5f, 0x69 };
    char restored[6];
    restored[0] = scrambled[0];
    restored[1] = scrambled[1];
    restored[2] = scrambled[3];
    restored[3] = scrambled[4];
    restored[4] = scrambled[2];
    restored[5] = scrambled[5];
    std::string chunk = std::string(restored, 6);
    cumulative_state += chunk;
    jump_history.push_back(chunk);
    update_state_matching();
}

// Jump function for Chunk 2: "fficil"
void jump_to_naples() {
    // Mangled storage with fixed PRNG seed (1339)
    char scrambled[6] = { 0x69, 0x69, 0x63, 0x66, 0x66, 0x6c };
    char restored[6];
    restored[0] = scrambled[4];
    restored[1] = scrambled[3];
    restored[2] = scrambled[0];
    restored[3] = scrambled[2];
    restored[4] = scrambled[1];
    restored[5] = scrambled[5];
    std::string chunk = std::string(restored, 6);
    cumulative_state += chunk;
    jump_history.push_back(chunk);
    update_state_matching();
}

// Jump function for Chunk 3: "e_ma_i"
void jump_to_verona() {
    // Mangled storage with fixed PRNG seed (1340)
    char scrambled[6] = { 0x5f, 0x61, 0x69, 0x6d, 0x5f, 0x65 };
    char restored[6];
    restored[0] = scrambled[5];
    restored[1] = scrambled[0];
    restored[2] = scrambled[3];
    restored[3] = scrambled[1];
    restored[4] = scrambled[4];
    restored[5] = scrambled[2];
    std::string chunk = std::string(restored, 6);
    cumulative_state += chunk;
    jump_history.push_back(chunk);
    update_state_matching();
}

// Jump function for Chunk 4: "o_sono"
void jump_to_palermo() {
    // Mangled storage with fixed PRNG seed (1341)
    char scrambled[6] = { 0x5f, 0x73, 0x6e, 0x6f, 0x6f, 0x6f };
    char restored[6];
    restored[0] = scrambled[5];
    restored[1] = scrambled[0];
    restored[2] = scrambled[1];
    restored[3] = scrambled[4];
    restored[4] = scrambled[2];
    restored[5] = scrambled[3];
    std::string chunk = std::string(restored, 6);
    cumulative_state += chunk;
    jump_history.push_back(chunk);
    update_state_matching();
}

// Jump function for Chunk 5: "_Mario"
void jump_to_milan() {
    // Mangled storage with fixed PRNG seed (1342)
    char scrambled[6] = { 0x6f, 0x5f, 0x69, 0x72, 0x4d, 0x61 };
    char restored[6];
    restored[0] = scrambled[1];
    restored[1] = scrambled[4];
    restored[2] = scrambled[5];
    restored[3] = scrambled[3];
    restored[4] = scrambled[2];
    restored[5] = scrambled[0];
    std::string chunk = std::string(restored, 6);
    cumulative_state += chunk;
    jump_history.push_back(chunk);
    update_state_matching();
}

// Revert function to roll back the last traversal step
void undo_jump() {
    if (!jump_history.empty()) {
        std::string last = jump_history.back();
        jump_history.pop_back();
        cumulative_state.resize(cumulative_state.length() - last.length());
        update_state_matching();
    }
}

int main() {
    std::cout << "=== Jump Around & Find Out CTF Challenge ===" << std::endl;
    std::cout << "Target sequence of 6 jump functions must be invoked in order." << std::endl;
    std::cout << "Use a debugger (e.g. GDB) to call functions and inspect step match flags." << std::endl;
    std::cout << "Press Enter to exit..." << std::endl;
    std::cin.get();
    return 0;
}
